### PR TITLE
fix(timestamps): generate timestamps correctly and remove the deprecated pytz

### PR DESCRIPTION
**Pull request by uptickmetachu**
## Describe your changes

- Fixed timestamp generation so that it correctly reflects the time at the timezone. Previously timestamps were generated with the local machine time `datetime.datetime.now()` and then set to the timezone. 
- I removed pytz as it is now deprecated since the inclusion of the built in zoneinfo

## Issue number and link
Closes https://github.com/echoboomer/incident-bot/issues/453

## Checklist before requesting a review

- [x] I have properly bumped all version refs by running `./scripts/version-bump.sh v<new>` from project root - for example `./scripts/version-bump.sh v1.9.3`

### CODE REVIEW

**Comment by rwejdling** [comment]
@echoboomer would it be possible to get this (or similar fix) in the next release?

**Comment by uptickmetachu** [comment]
@echoboomer I've rebased this and bumped to v1.10.8

Would love to have this one reviewed / merged before I do the confluence one.

**Comment by echoboomer** [comment]
Looks like this will need some changes.

**Comment by uptickmetachu** [comment]
https://docs.python.org/3/library/datetime.html#technical-detail

>%Z
In strftime(), %Z is replaced by an empty string if tzname() returns None; otherwise %Z is replaced by the returned value, which must be a string.
>strptime() only accepts certain values for %Z:
>any value in time.tzname for your machine’s locale
>the hard-coded values UTC and GMT
>So someone living in Japan may have JST, UTC, and GMT as valid values, but probably not EST. It will raise ValueError for invalid values.

Mmmm using `%Z` in the output format means we won't be able to reparse the time (if it is not UTC formatted).

**Comment by uptickmetachu** [comment]
And another problem;

When we do parse the datetime with `strptime` it will be stored as a timezone naive datetime object. These objects
are then compared against other date time naive objects.
Eg:

https://github.com/echoboomer/incident-bot/blob/4126c4c3e9ba77a1186a9dc256c10a4c4717bf13/backend/bot/scheduler/scheduler.py#L90C1-L97C2

Should I modify this PR to ensure all timezones are datetime aware?

**Comment by echoboomer** [comment]
I guess? Seems like that is logical.

**Pull request closed without merging**
